# -*- coding: utf-8 -*-
"""Cópia de Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycwHgh2ZIWEqJVO2oL4glSK_mSaU9lN_

# Nova seção
"""

print(df_mobs.columns)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df_mobs = pd.read_csv('Mobs.csv')

df_mobs['healthPoints'] = pd.to_numeric(df_mobs['healthPoints'], errors='coerce')
df_mobs.dropna(subset=['healthPoints'], inplace=True)

plt.figure(figsize=(10, 6))
sns.histplot(df_mobs['healthPoints'], bins=10, kde=False)
plt.title('Histograma da Vida dos Mobs', fontsize=16)
plt.xlabel('Vida (Health Points)', fontsize=12)
plt.ylabel('Frequência', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(df_mobs['healthPoints'], fill=True)
plt.title('Curva de Densidade de Dados (KDE) da Vida dos Mobs', fontsize=16)
plt.xlabel('Vida (Health Points)', fontsize=12)
plt.ylabel('Densidade', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x=df_mobs['healthPoints'])
plt.title('Boxplot da Vida dos Mobs (com Outliers)', fontsize=16)
plt.xlabel('Vida (Health Points)', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x=df_mobs['healthPoints'], whis=[0, 100])
plt.title('Boxplot da Vida dos Mobs (sem Outliers)', fontsize=16)
plt.xlabel('Vida (Health Points)', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()